"""initial migration

Revision ID: 529362a52321
Revises: 15c420158efd
Create Date: 2020-06-01 20:44:55.986494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529362a52321'
down_revision = '15c420158efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
